bump language in when processing shadow-js
Closure compilation failed with 1 errors
--- node_modules/dialog-polyfill/dialog-polyfill.js:692
this language feature is only supported for ECMASCRIPT6 mode or better:
block-scoped function declaration. Use --language_in=ECMASCRIPT6 or
ECMASCRIPT6_STRICT or higher to enable ES6 features.

errors out since

https://github.com/google/closure-compiler/commit/41331b3d98612101fe09bd01bdd5b305526281e5